# Generated by Django 4.0.6 on 2023-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='work',
            new_name='works',
        ),
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('YT', 'Youtube'), ('IT', 'Instagram'), ('OT', 'Other')], max_length=2),
        ),
    ]
